## Numpy array and basics

import numpy as np

In [2]:
import numpy as np 

### creating array from list


In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: \n", arr_2d)

1D array:  [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [5]:
py_list = [1,2,3,4,5]
print("Python List multiplication : ",py_list*2)


np_array= np.array([1,2,3,4,5])
print("Numpy Array multiplication : ",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python list time: ", time.time()-start)

start = time.time()
np_array= np.arange(1000000)*2
print("Numpy array time: ", time.time()-start)



Python List multiplication :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array multiplication :  [ 2  4  6  8 10]
Python list time:  0.16156744956970215
Numpy array time:  0.018683433532714844


### Creating array from Scratch

In [9]:
zeros = np.zeros((3,4))
print("Array of Zeros: \n", zeros)

ones = np.ones((3,4))
print("Array of Ones: \n", ones)

full = np.full((3,4), 7)
print("Array of Full: \n", full)

eye = np.eye(4)
print("Identity Matrix: \n", eye)

random = np.random.random((3,4))
print("Array of Randoms: \n", random)

sequence = np.arange(10,21,2)
print("Sequence Array: \n", sequence)



Array of Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of Full: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array of Randoms: 
 [[0.04629931 0.72462682 0.38831851 0.50240804]
 [0.39092134 0.06435747 0.07534591 0.47313726]
 [0.86141347 0.33241877 0.10921156 0.58069435]]
Sequence Array: 
 [10 12 14 16 18 20]


### Vector , Matrix, Tensor

In [10]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int64


### Array Reshaping

In [18]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled array ", raveled)

#Transpose
transpose = reshaped.T
print("Transposed array \n", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
