## NumPy Array operations

In [13]:
import numpy as np

In [14]:
arr = np.arange(1,11) # 1 to 10, 11 not included
print("Basic Slicing:", arr[2:7])
print("with Step:", arr[1:8:2])
print("Negative indexing: ", arr[-8:-3]) # last 8 to last 3
print("Negative indexing: ", arr[-3])

Basic Slicing: [3 4 5 6 7]
with Step: [2 4 6 8]
Negative indexing:  [3 4 5 6 7]
Negative indexing:  8


## 2D array

In [15]:
arr_2d = np.array([1,2,3,4,5,6,7,8,9]) # 1D array
arr_2d = arr_2d.reshape(3,3) # 2D array 0,1,2
print(arr_2d)

print("Specific element: ", arr_2d[1,2])
print("Specific row: ", arr_2d[1]) # 2nd row
print("Specific column: ", arr_2d[:,1]) # all rows, 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  6
Specific row:  [4 5 6]
Specific column:  [2 5 8]


# Sorting


In [16]:
unsorted_arr = np.array([3,1,4,5,2,1,3])
print("Sorted Array: ", np.sort(unsorted_arr) )

arr_2d_unsorted = np.array([[3,1], [1,2],[2,3]])
print("Original\n", arr_2d_unsorted)
print("Sorted 2d array by column:\n ", np.sort(arr_2d_unsorted, axis=0))
print("Array 2d array by Row:\n ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 3 3 4 5]
Original
 [[3 1]
 [1 2]
 [2 3]]
Sorted 2d array by column:
  [[1 1]
 [2 2]
 [3 3]]
Array 2d array by Row:
  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number%2==0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [18]:
mask = number > 5 
print("Numbers greater than 5: ", number[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [19]:
indices = [0,2,4]
print("Fancy Indexing: ", number[indices])

where_result = np.where(number>5)
print("Using np.where(): ", number[where_result])


Fancy Indexing:  [1 3 5]
Using np.where():  [ 6  7  8  9 10]


In [25]:
condition_array = np.where(number > 5, number*2, number)
print("Conditional Array  : ", condition_array)

condition_array = np.where(number > 5, "true", "false")
print("Conditional Array  : ", condition_array)

Conditional Array  :  [ 1  2  3  4  5 12 14 16 18 20]
Conditional Array  :  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## if(numbers>5){
  ##  number* 2
## } else {
   ## numbers
## }  

### Adding and removing data

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1, arr2))
print("Combined Array: ", combined_arr)

Combined Array:  [1 2 3 4 5 6]


### Array Compatibility

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatbility: ", a.shape == b.shape == c.shape)

compatbility:  True


In [29]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)# delete index 2
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
