In [10]:
import numpy as np
import matplotlib.pyplot as plt

### Data

In [11]:
# Data Structure: [restauurant_id, 2021,2022,2023,2024]

sales_data = np.array([
    [1, 50000, 55000, 60000, 65000],
    [2, 70000, 72000, 75000, 80000],
    [3, 30000, 35000, 40000, 45000],
    [4, 90000, 95000, 100000, 110000],
    [5, 40000, 45000, 50000, 60000]
])
print("\n Sales data shape", sales_data.shape)
print("\n Sales data of 1st 3 rest.", sales_data[0:3])


print(np.sum(sales_data, axis=0))

yearly_total= np.sum(sales_data[:, 1:], axis=0) # all rows, skip 1(0) coln only(means restaurant id 1,,2,3,4,5)
print(yearly_total)

# Minimum sales per restaurant
min_sales = np.min(sales_data[:, 1:],axis=1)
print("min_sales", min_sales)

# Average sales per restaurant
avg_sales = np.mean(sales_data[: , 1:],axis=1)
print("avg", avg_sales)


 Sales data shape (5, 5)

 Sales data of 1st 3 rest. [[    1 50000 55000 60000 65000]
 [    2 70000 72000 75000 80000]
 [    3 30000 35000 40000 45000]]
[    15 280000 302000 325000 360000]
[280000 302000 325000 360000]
min_sales [50000 70000 30000 90000 40000]
avg [57500. 74250. 37500. 98750. 48750.]


In [12]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

print("Vector addition", vector1 + vector2)

print("\n Multiplication vector", vector1*vector2)

print("\n Dot Product", np.dot(vector1,vector2))

angle = np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(" Angle ", angle)

Vector addition [ 7  9 11 13 15]

 Multiplication vector [ 6 14 24 36 50]

 Dot Product 130
 Angle  0.26554161733900966


In [13]:
restaurant_type= np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorizesd_upper =np.vectorize(str.upper)

print(vectorizesd_upper(restaurant_type))

['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [15]:
monthly_avg = sales_data[:, 1:] /12
print(monthly_avg)

[[4166.66666667 4583.33333333 5000.         5416.66666667]
 [5833.33333333 6000.         6250.         6666.66666667]
 [2500.         2916.66666667 3333.33333333 3750.        ]
 [7500.         7916.66666667 8333.33333333 9166.66666667]
 [3333.33333333 3750.         4166.66666667 5000.        ]]
